# kubectl create secret tls jupiterpi-de-tls -cert=***** -key=*****

apiVersion: apps/v1
kind: Deployment
metadata:
  name: majesty-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: majesty-client
  template:
    metadata:
      labels:
        app: majesty-client
    spec:
      containers:
        - name: majesty-client
          image: jupiterpi/majesty-client
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: majesty-client
spec:
  type: LoadBalancer
  selector:
    app: majesty-client
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: majesty-client
spec:
  ingressClassName: public
  tls:
    - hosts:
        - majesty.jupiterpi.de
      secretName: jupiterpi-de-tls
  rules:
    - host: "majesty.jupiterpi.de"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: majesty-client
                port:
                  number: 80
