runtime: nodejs16

service: majesty-client

handlers:
  - url: /(.*\..+)$
    static_files: dist/majesty-client/\1
    upload: dist/majesty-client/(.*\..+)$
  - url: /.*
    static_files: dist/majesty-client/index.html
    upload: dist/majesty-client/index.html

# as by https://medium.com/@rgoyard/how-to-deploy-a-single-page-application-and-its-backend-to-google-app-engine-353ff93bd38c
