name: Deploy majesty-client

on:
  push:
    branches: [ "main" ]
    paths:
    - majesty-client/**
  pull_request:
    branches: [ "main" ]
    paths:
    - majesty-client/**

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.run_number }}
    steps:
    
    - uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        push: true
        tags: jupiterpi/majesty-client:${{ env.IMAGE_TAG }}
    
    - name: Replace tokens in Kubernetes files
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["kubernetes/*"]'
      env:
        IMAGE_TAG: ${{ env.IMAGE_TAG }}

    - name: Deploy to Kubernetes
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://kube-cd.jupiterpi.de/applyKubernetesResource/majesty-client-githubactions/majesty-client.yaml'
        method: POST
        customHeaders: '{"Authorization": "Bearer ${{ secrets.KUBE_CD_TOKEN }}"}'
        contentType: text/plain
        file: kubernetes/majesty-client.yaml